### ISSUE TITLE
这个脚本也只支持win啊，mac下跑不起来

### ISSUE THREAD

**Issue by dengcb** [asxez/DDCS#1]
`Traceback (most recent call last):
  File "/Users/deng/Downloads/DDCS/ddcs.py", line 11, in <module>
    from lib.processor import DDProcessor, FileProcessor
  File "/Users/deng/Downloads/DDCS/lib/processor.py", line 15, in <module>
    import winreg
ModuleNotFoundError: No module named 'winreg'`

**Comment by asxez** [comment]
Mac版本预计九月初左右发布，敬请期待。

**Comment by asxez** [comment]
> `Traceback (most recent call last):
>   File "/Users/deng/Downloads/DDCS/ddcs.py", line 11, in <module>
>     from lib.processor import DDProcessor, FileProcessor
>   File "/Users/deng/Downloads/DDCS/lib/processor.py", line 15, in <module>
>     import winreg
> ModuleNotFoundError: No module named 'winreg'`

Mac版本预计九月初左右发布，敬请期待。

**Comment by asxez** [comment]
> `Traceback (most recent call last): File "/Users/deng/Downloads/DDCS/ddcs.py", line 11, in <module> from lib.processor import DDProcessor, FileProcessor File "/Users/deng/Downloads/DDCS/lib/processor.py", line 15, in <module> import winreg ModuleNotFoundError: No module named 'winreg'`

原计划于9月初发布的DDCS-MAC将提前发布，预计8月14日左右，敬请期待。

**Comment by dengcb** [comment]
测试通过！`共耗时：14.16384808s`
还有些地方，没有100%中文化，我们可以出点力吗？

**Comment by asxez** [comment]
> 测试通过！`共耗时：14.16384808s` 还有些地方，没有100%中文化，我们可以出点力吗？

可以的，解包后会生成一个“app”文件夹，这里面找关键词，然后添加到config.json文件就行了，修改测试通过后提交pr即可。
