### ISSUE TITLE
此脚本需要node 环境和 asar 

### ISSUE THREAD

**Issue by fanrujiang** [asxez/DDCS#15]
如题，建议优化脚本和简要说明 需要的环境

**Comment by asxez** [comment]
> 如题，建议优化脚本和简要说明 需要的环境

哈哈哈哈一直说改，但是每次都忘。

**Comment by asxez** [comment]
> > 如题，建议优化脚本和简要说明 需要的环境
> 
> 哈哈哈哈一直说改，但是每次都忘。

已更新

**Comment by fanrujiang** [comment]
> > > 如题，建议优化脚本和简要说明 需要的环境
> > 
> > 
> > 哈哈哈哈一直说改，但是每次都忘。
> 
> 已更新

有个小问题 应该是全局安装 
npm install -g asar
